# Generated by Django 6.0.3 on 2026-03-23 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=255)),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gender', models.CharField(choices=[('G', 'Girls'), ('B', 'Boys')], max_length=1)),
                ('stars', models.IntegerField(default=5)),
                ('has_wifi', models.BooleanField(default=True)),
                ('has_cctv', models.BooleanField(default=True)),
                ('has_food', models.BooleanField(default=False)),
                ('has_cleaning', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hostels/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.owner')),
            ],
        ),
    ]
