# Generated by Django 6.0.4 on 2026-05-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_house'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('check_in_date', models.DateField(blank=True, null=True)),
                ('number_of_roommates', models.IntegerField(default=0)),
                ('stay_duration', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('parent_phone_number', models.CharField(blank=True, max_length=20)),
                ('nid_or_passport', models.CharField(blank=True, max_length=100)),
                ('emergency_contact', models.CharField(blank=True, max_length=20)),
                ('copy_id_number', models.CharField(blank=True, max_length=100)),
                ('draft_email_address', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_for', models.CharField(max_length=50)),
                ('property_type', models.CharField(max_length=100)),
                ('size', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('tenant_type', models.CharField(blank=True, max_length=100)),
                ('monthly_rent_min', models.CharField(blank=True, max_length=100)),
                ('monthly_rent_max', models.CharField(blank=True, max_length=100)),
                ('room_type', models.CharField(blank=True, max_length=100)),
                ('gender_requirement', models.CharField(blank=True, max_length=100)),
                ('roommate_characteristics', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=50)),
                ('rating', models.IntegerField(default=0)),
                ('complaint', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequirementAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_no', models.CharField(max_length=20)),
                ('requirement', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('language', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
