# Generated by Django 6.0.4 on 2026-05-07 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_applicationform_id_alter_bookingrequest_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoysHostel',
            fields=[
            ],
            options={
                'verbose_name': 'Boys Hostel',
                'verbose_name_plural': 'Boys Hostel List',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.hostel',),
        ),
        migrations.CreateModel(
            name='GirlsHostel',
            fields=[
            ],
            options={
                'verbose_name': 'Girls Hostel',
                'verbose_name_plural': 'Girls Hostel List',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.hostel',),
        ),
    ]
