# Generated by Django 5.2.5 on 2026-05-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_applicationform_id_alter_bookingrequest_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='stars',
        ),
        migrations.AddField(
            model_name='hostel',
            name='facilities_list',
            field=models.TextField(blank=True, help_text='Enter other facilities (one per line)', null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='meal_plan',
            field=models.TextField(blank=True, help_text='Describe the meal system and menu', null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='room_details',
            field=models.CharField(blank=True, help_text='e.g. 3-Bed Sharing (Spacious Room)', max_length=255, null=True),
        ),
    ]
