# Generated by Django 5.2.5 on 2026-05-07 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_hostel_stars_hostel_facilities_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='has_cctv',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='has_cleaning',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='has_food',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='has_wifi',
        ),
    ]
