# Generated by Django 5.2.5 on 2026-05-08 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_hostel_has_cctv_remove_hostel_has_cleaning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
