# Generated by Django 5.2.5 on 2026-05-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='facilities',
            field=models.TextField(blank=True, help_text='Enter facilities separated by commas', null=True),
        ),
    ]
