# Generated by Django 5.2.5 on 2026-05-09 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_house_facilities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('check_in_date', models.DateField()),
                ('roommates_count', models.IntegerField(default=0)),
                ('stay_duration', models.CharField(max_length=100)),
                ('current_address', models.TextField()),
                ('own_phone', models.CharField(max_length=20)),
                ('guardian_phone', models.CharField(max_length=20)),
                ('nid_number', models.CharField(max_length=50)),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('hostel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.hostel')),
                ('house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.house')),
            ],
        ),
    ]
