# Generated by Django 5.2.5 on 2026-05-09 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_feedback_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentfeedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentfeedback',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentfeedback',
            name='complaint',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentfeedback',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BKASH', 'bKash'), ('ATM', 'ATM')], max_length=10),
        ),
        migrations.AlterField(
            model_name='paymentfeedback',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
