# Generated by Django 5.2.5 on 2026-05-09 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_paymentfeedback_created_at_paymentfeedback_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentfeedback',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
